[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
project-root = "0.2.2"
dotenv = "0.14.1"
base64 = "0.13.0"
reqwest = "0.11.11"
